# Generated by Django 5.2.7 on 2026-01-05 10:22

from django.db import migrations


def fix_category_slugs(apps, schema_editor):
    """Fix slugs for Accessories, Bracelets, and Earrings categories that have numeric slugs."""
    Category = apps.get_model('ecommerce', 'Category')
    
    # Map category names to their correct slugs
    category_slugs = {
        'Accessories': 'accessories',
        'Bracelets': 'bracelets',
        'Earrings': 'earrings',
    }
    
    for cat_name, expected_slug in category_slugs.items():
        try:
            # Use only() to avoid parent field issues
            cat = Category.objects.only('id', 'name', 'slug').get(name=cat_name)
            
            # Check if slug needs fixing (empty, numeric, or wrong)
            if not cat.slug or cat.slug.isdigit() or cat.slug != expected_slug:
                # Check if expected slug is already taken by another category
                existing = Category.objects.only('id', 'slug').filter(slug=expected_slug).exclude(pk=cat.pk).first()
                if existing:
                    # Generate unique slug if needed
                    counter = 1
                    new_slug = f"{expected_slug}-{counter}"
                    while Category.objects.only('id', 'slug').filter(slug=new_slug).exclude(pk=cat.pk).exists():
                        counter += 1
                        new_slug = f"{expected_slug}-{counter}"
                    Category.objects.filter(pk=cat.pk).update(slug=new_slug)
                else:
                    Category.objects.filter(pk=cat.pk).update(slug=expected_slug)
        except Category.DoesNotExist:
            # Category doesn't exist, skip
            pass
        except Category.MultipleObjectsReturned:
            # Multiple categories with same name, skip (shouldn't happen)
            pass


def reverse_fix_category_slugs(apps, schema_editor):
    """Reverse migration - set slugs back to numeric if they were numeric before."""
    # We can't really reverse this, so just pass
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0017_add_product_slug"),
    ]

    operations = [
        migrations.RunPython(fix_category_slugs, reverse_fix_category_slugs),
    ]
