# Generated by Django 5.2.7 on 2026-01-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0018_fix_category_slugs_accessories_bracelets_earrings"),
    ]

    operations = [
        migrations.AddField(
            model_name="bannerimage",
            name="video_file",
            field=models.FileField(
                blank=True,
                help_text="Upload a video file (MP4, WebM, OGG). Video will autoplay, loop, and be muted like a GIF. Max size: 100MB",
                null=True,
                upload_to="banners/videos/",
            ),
        ),
        migrations.AlterField(
            model_name="bannerimage",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Banner image for carousel",
                null=True,
                upload_to="banners/",
            ),
        ),
    ]
